services:
  agent:
    build:
      context: .
      dockerfile: ./agent/Dockerfile
    container_name: agent-service
    env_file:
      - ./agent/.env
    ports:
      - "8002:8000" # host:container
    command: python -m uvicorn agent.main:app --host 0.0.0.0 --port 8000

  auth:
    build:
      context: .
      dockerfile: ./backend/auth_service/Dockerfile
    container_name: auth-service
    env_file:
      - ./backend/auth_service/.env
    ports:
      - "8000:8000"
    command: python -m uvicorn auth_service.main:app --host 0.0.0.0 --port 8000

  documents:
    build:
      context: .
      dockerfile: ./backend/documents_service/Dockerfile
    container_name: documents-service
    env_file:
      - ./backend/documents_service/.env
    ports:
      - "8001:8000"
    command: python -m uvicorn documents_service.main:app --host 0.0.0.0 --port 8000

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8000"   # host 8080: gateway 8000
    depends_on:
      - auth
      - documents
      - agent
    command: python -m uvicorn gateway.main:app --host 0.0.0.0 --port 8000