name: Build and deploy Angular app to Azure Web App - apprecruita

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: frontend/recruita/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend/recruita
          npm ci

      - name: Build Angular app
        run: |
          cd frontend/recruita
          npm run build --if-present

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: frontend/recruita/dist/recruita/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app
          path: ./angular-app

      - name: Add web.config for Angular routing
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>' > ./angular-app/web.config
          echo '<configuration>' >> ./angular-app/web.config
          echo '  <system.webServer>' >> ./angular-app/web.config
          echo '    <rewrite>' >> ./angular-app/web.config
          echo '      <rules>' >> ./angular-app/web.config
          echo '        <rule name="Angular Routes" stopProcessing="true">' >> ./angular-app/web.config
          echo '          <match url=".*" />' >> ./angular-app/web.config
          echo '          <conditions logicalGrouping="MatchAll">' >> ./angular-app/web.config
          echo '            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />' >> ./angular-app/web.config
          echo '            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />' >> ./angular-app/web.config
          echo '          </conditions>' >> ./angular-app/web.config
          echo '          <action type="Rewrite" url="/index.html" />' >> ./angular-app/web.config
          echo '        </rule>' >> ./angular-app/web.config
          echo '      </rules>' >> ./angular-app/web.config
          echo '    </rewrite>' >> ./angular-app/web.config
          echo '  </system.webServer>' >> ./angular-app/web.config
          echo '</configuration>' >> ./angular-app/web.config

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_78ADF64D47B74DA6B89B3AEE6DBA7E5C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D02220372B8244909368864932DC53EE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7A65D12ACA2C4696982F5B4C18D33291 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'apprecruita'
          slot-name: 'Production'
          package: ./angular-app
